===============LOGIN=================
curl \
--header "Content-Type: application/json" \
--request POST \
--data '{"email":"bobby@chat.com", "password":"rahasia"}' \
http://192.168.1.7:8000/auth/login


===============SIGNUP=================
curl \
--header "Content-Type: application/json" \
--request POST \
--data '{"username":"angie", "email":"angie@irawan.com", "password":"rahasia"}' \
http://192.168.1.7:8000/auth/signup

===============CREATE CONTACT=================
curl \
--header "Content-Type: application/json" \
--request POST \
--data '{
    "user_id":"bfccdfc7-d2b5-4c4c-b9fb-8153cc856ff9", 
    "username":"cindy", 
    "email":"cindy@irawan.com"
    }' \
http://192.168.1.3:8000/contact

===============CREATE CONTACT=================
curl \
--request GET \
http://192.168.1.3:8000/contact/bfccdfc7-d2b5-4c4c-b9fb-8153cc856ff9

===============GET USER BY ID=================
curl \
--request GET \
http://192.168.1.7:8000/user/user/bfccdfc7-d2b5-4c4c-b9fb-8153cc856ff9

===============Get List Chat=================
curl \
--request GET \
http://192.168.1.6:8000/chats?user_id=bfccdfc7-d2b5-4c4c-b9fb-8153cc856ff9

===============GET LIST CHAT USER BY Chat ID================= tidak bisa menggunakan curl karena mengandung & dan ?, curl mendeteksi sebagai regex
curl \
--request GET \
http://192.168.1.6:8000/chats/listchat?chat_id=72b84e9c-f65e-4835-aa58-2a1f2185fff4





